## Numpy - Data Analysis
### Two dimension array 

In [ ]:
#### Shape ,Reshape , Random ,linspace ,Arange ,Unique , Flip , Transpose 

In [1]:
import numpy as np


In [4]:
a=np.array ([[1,2,4,5],[1,2,3,4]])

In [9]:
a

array([[1, 2, 4, 5],
       [1, 2, 3, 4]])

### (row,column )

In [6]:
a[0][0]

1

In [8]:
a[1][3]

4

In [10]:
b=a[0:]


In [11]:
b

array([[1, 2, 4, 5],
       [1, 2, 3, 4]])

In [12]:
b=a[0,:]
b

array([1, 2, 4, 5])

In [14]:
c=a[0:2 ,0:3]
c 

array([[1, 2, 4],
       [1, 2, 3]])

In [15]:
c=a[: ,0:3]
c 

array([[1, 2, 4],
       [1, 2, 3]])

In [16]:
c[0][0]=100

In [17]:
c

array([[100,   2,   4],
       [  1,   2,   3]])

In [18]:
a

array([[100,   2,   4,   5],
       [  1,   2,   3,   4]])

In [19]:
v=a.copy ()
v

array([[100,   2,   4,   5],
       [  1,   2,   3,   4]])

In [20]:
v[0][0]=150 

In [21]:
v 

array([[150,   2,   4,   5],
       [  1,   2,   3,   4]])

In [22]:
a

array([[100,   2,   4,   5],
       [  1,   2,   3,   4]])

#### Create random numbers 

In [23]:
a=np.random .random (20 )

In [24]:
a 

array([0.92330405, 0.17816391, 0.35284323, 0.77672338, 0.2399222 ,
       0.8550556 , 0.90099954, 0.47188479, 0.90946713, 0.58181508,
       0.7603419 , 0.88376113, 0.15579567, 0.18374959, 0.60952714,
       0.12718767, 0.15549459, 0.00531827, 0.03773985, 0.34462857])

In [25]:
np.linspace(1,10,7 )

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [26]:
np.linspace(0,20,10 )

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
np.linspace(1,10,1 )

array([1.])

In [30]:
np.arange(1,10,1 )

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10,1.2 )

array([1. , 2.2, 3.4, 4.6, 5.8, 7. , 8.2, 9.4])

In [33]:
np.zeros(10 )

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.ones(10 )

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones([2,4] )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.ones([4,3] )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
a

array([0.92330405, 0.17816391, 0.35284323, 0.77672338, 0.2399222 ,
       0.8550556 , 0.90099954, 0.47188479, 0.90946713, 0.58181508,
       0.7603419 , 0.88376113, 0.15579567, 0.18374959, 0.60952714,
       0.12718767, 0.15549459, 0.00531827, 0.03773985, 0.34462857])

In [50]:
a.ndim 

1

In [46]:
c

array([[100,   2,   4],
       [  1,   2,   3]])

In [51]:
c.ndim

2

In [52]:
a.shape

(20,)

In [53]:
c.shape

(2, 3)

In [54]:
type (c)

numpy.ndarray

In [56]:
c.dtype 

dtype('int32')

In [57]:
a.shape

(20,)

In [58]:
a

array([0.92330405, 0.17816391, 0.35284323, 0.77672338, 0.2399222 ,
       0.8550556 , 0.90099954, 0.47188479, 0.90946713, 0.58181508,
       0.7603419 , 0.88376113, 0.15579567, 0.18374959, 0.60952714,
       0.12718767, 0.15549459, 0.00531827, 0.03773985, 0.34462857])

In [59]:
d=a.reshape(4,5)

In [60]:
d

array([[0.92330405, 0.17816391, 0.35284323, 0.77672338, 0.2399222 ],
       [0.8550556 , 0.90099954, 0.47188479, 0.90946713, 0.58181508],
       [0.7603419 , 0.88376113, 0.15579567, 0.18374959, 0.60952714],
       [0.12718767, 0.15549459, 0.00531827, 0.03773985, 0.34462857]])

In [61]:
d.shape

(4, 5)

In [62]:
a.shape

(20,)

In [63]:
d.ndim

2

In [64]:
d=a.reshape(5,4)

In [65]:
d

array([[0.92330405, 0.17816391, 0.35284323, 0.77672338],
       [0.2399222 , 0.8550556 , 0.90099954, 0.47188479],
       [0.90946713, 0.58181508, 0.7603419 , 0.88376113],
       [0.15579567, 0.18374959, 0.60952714, 0.12718767],
       [0.15549459, 0.00531827, 0.03773985, 0.34462857]])

In [70]:
n=np.array([91,2,3,4,5,6,7,8,9,7,66,6,655]) 
n

array([ 91,   2,   3,   4,   5,   6,   7,   8,   9,   7,  66,   6, 655])

In [71]:
np.unique (n )

array([  2,   3,   4,   5,   6,   7,   8,   9,  66,  91, 655])

In [72]:
n.sum ()

869

In [73]:
n+1

array([ 92,   3,   4,   5,   6,   7,   8,   9,  10,   8,  67,   7, 656])

In [75]:
random1 =np.random.random  ([3,5])
random2 =np.random.random  ([3,5])

In [76]:
random1 

array([[0.06833176, 0.21355058, 0.91014807, 0.08693659, 0.14753928],
       [0.03468576, 0.79640135, 0.79037248, 0.85860109, 0.95029045],
       [0.16207629, 0.78613033, 0.21642698, 0.65728973, 0.97939092]])

In [77]:
random2

array([[0.17317685, 0.43733361, 0.03457515, 0.04880075, 0.61616787],
       [0.92351812, 0.6903341 , 0.36263481, 0.35586543, 0.88677947],
       [0.00199057, 0.46658931, 0.05305875, 0.73717769, 0.12151632]])

In [78]:
randomsum=random1 +random2 

array([[0.24150861, 0.65088419, 0.94472322, 0.13573733, 0.76370715],
       [0.95820388, 1.48673545, 1.15300729, 1.21446652, 1.83706992],
       [0.16406687, 1.25271964, 0.26948573, 1.39446742, 1.10090724]])

In [80]:
random_normal=random1/random2.max()

In [81]:
random_normal

array([[0.07399071, 0.23123594, 0.98552269, 0.09413631, 0.15975786],
       [0.03755829, 0.86235595, 0.8558278 , 0.92970681, 1.0289895 ],
       [0.17549877, 0.85123433, 0.23435055, 0.71172369, 1.06049995]])

In [82]:
np.sqrt(100)

10.0

In [83]:
np.sqrt(100).astype (int)

10

In [84]:
w=np.arange (1,30,1)

In [85]:
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
w=np.arange (1,31,1)
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [89]:
w=w.reshape (5,6)

In [90]:
w

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [93]:
e=np.flip(w)

In [94]:
e

array([[30, 29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [96]:
e.sort ()

In [97]:
e

array([[25, 26, 27, 28, 29, 30],
       [19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [98]:
e.transpose ()

array([[25, 19, 13,  7,  1],
       [26, 20, 14,  8,  2],
       [27, 21, 15,  9,  3],
       [28, 22, 16, 10,  4],
       [29, 23, 17, 11,  5],
       [30, 24, 18, 12,  6]])